### ISSUE TITLE
Vibey-Spotify token juggling

### ISSUE THREAD

**Issue by s-munro** [hrishikeshpaul/vibey#24]
re: https://www.reddit.com/r/AskNetsec/comments/g4s9b6/can_i_leverage_spotify_authorization_for_my_apps/

Spotify's access token evidently has a lifetime of one hour, and can be supplemented with a seemingly permanent refresh token
<img width="981" alt="Screen Shot 2021-04-11 at 11 19 31 PM" src="https://user-images.githubusercontent.com/68410363/114336189-61f88a80-9b1c-11eb-9114-0f3dcf67fec2.png">

In order to use our own tokens and the spotify tokens in conjunction with one another, we need to make sure that a user can always access spotify for as long as they are signed into vibey, and that we are capable of finding a user's corresponding spotify tokens on our back-end whenever they make a spotify-related request

The first consideration (being able to access Spotify while signed into vibey) should be fine, since the spotify refresh token is supposedly indefinite.  A user should always be able to make spotify requests so long as we can find their token (and so long as Spotify doesn't rate-limit check us).

When a user makes authorization requests, our backend should first validate the jet.  If it needs refreshed, the frontend makes the refresh call, and vibey needs to encode the user's id into the new access token.  We can do this just by decoding the supplied access token, taking the user id from it, and re-encrypting it into the new jwt.

***Will blacklisting still be necessary?*** Blacklisting is done so that when a user 'signs out' we ensure their token can no-longer be used for anything.  This includes refresh tokens.  I believe we should still blacklist tokens on logout. Additionally, since all logins are done through Spotify, I'm thinking that we might need to remove the user's spotify tokens from redis on logout as well.  Ideally, we should probably do this, since if a user signs out of vibey we should not be able to make spotify requests on their behalf.

***Relevant middleware and edge cases*** Currently our middlewares check for tampered jwts and expired jwts.

## Paul's edits

I summed it up in a diagram. Let me know if this is what you were thinking.

![vibey auth](https://user-images.githubusercontent.com/22999894/114338755-bf430a80-9b21-11eb-87c3-c940f576c0f8.png)

**Comment by s-munro** [comment]
@hrishikeshpaul is this issue closed now?  I think it is, since we pushed that last PR

**Comment by hrishikeshpaul** [comment]
Yep this should be done (FINALLY)
