### ISSUE TITLE
Create a check route

### ISSUE THREAD

**Issue by hrishikeshpaul** [hrishikeshpaul/vibey#41]
When the user logs into the app, the app needs to decided whether it needs to render the AuthenticatedApp or the UnAuthenticatedApp. The way it would do this is in the `useEffect` of the app, it will make a request to the `/check` route.

Below are the scenarios,

1. If the AT isn't present then render Unaunthenticated app.
2. If the AT is present, then send it to the `/check` route. If it returns a 403, call `/refresh`. If theres no RT -> Unauth App. If RT isnt valid then -> unauth app.
3. Return a 200 and update the new AT/RT.

After which the authenticated app will be rendered, which will route to the respective room or home. This handles the case when the user refreshes on the page.

What do you think?

**Comment by s-munro** [comment]
Just worked to implement.  Only gray zone right now is whether I should have refreshed the tokens on a successful check - although I don't think so - I think that could be giving a lot of unnecessary traffic to redis.  Instead, I just have it check for the validity of the token, and return 204 OK if all is good.
