### ISSUE TITLE
Using camel case on the backend

### ISSUE THREAD

**Issue by hrishikeshpaul** [hrishikeshpaul/vibey#42]
The frontend makes a big deal if its not in camel case. For example the `display_name`. Is it possible to use camel case on the backend aswell? @s-munro

**Comment by s-munro** [comment]
Yeah it should all be camel cased on the backend as well - if I haven't then it's probably because I've been working in Python too much (lol..).  Were there any particular cases you noticed where it wasn't in camelcase?

**Comment by hrishikeshpaul** [comment]
Yeah the `display_name`. I was trying to use the profile route on the frontend and i saw that the object from the backend had `display_name` as a property. So i had to do
```
profile.displayName = profile.display_name
```
when i had to use it just so that the liter doesnt complain

**Comment by s-munro** [comment]
Oh whoops, yeah I'll submit a quick fix for that and tag you
