### ISSUE TITLE
As a host, I should be able to edit the details of my current room

### ISSUE THREAD

**Issue by hrishikeshpaul** [hrishikeshpaul/vibey#63]
### Information

The use should be able to click on the the `edit` button and edit the `name`, `description` and `tags` of the room.

#### Backend
1. `/rooms` - PUT - API to edit the details. Takes in the `_id` and the details mentioned above.
2. After saving it onto mongo, return a 204 (no content) and emit a socket signal `update-room` to update the details of the room for all the users in the room.
3. Send a 400/500 error via the API response if there is an error (don't emit a signal if there is an error).

#### Frontend
1. Create an `EditRoom.tsx` component that will be there in the `Room` component. 
2. Take in the room data from the store (or pass it as prop)
3. The submit should dispatch an action that calls the above mentioned api.
4. Create a socket subscription signal to listen to `update-room` and dispatch an `updateRoom` action.

**Comment by hrishikeshpaul** [comment]
@s-munro thoughts?

**Comment by s-munro** [comment]
Yeah this sounds solid to me.  Going to look into #64 then hop into this, since I'm sure the redis fix will only take a brief amount of time.
