### ISSUE TITLE
Change the data stored in the redis

### ISSUE THREAD

**Issue by hrishikeshpaul** [hrishikeshpaul/vibey#64]
The roomId should be mapped to the following data:
1. The IDs of the current users in room
2. The current track (track should have the position, duration, uri, name, artist, image url, state (paused/playing)).  Take a look at the track on the FE for more info

From what i've read, Redis is the most efficient (space and memory wise) when stuff is stores as strings. It turns out that stringifying it and parsing it could be a great way. 

For stringify i found this - https://github.com/fastify/fast-json-stringify
For parsing i found - https://github.com/alemures/fast-json

Not sure how compatible with TS, but I've read that the native `JSON.parse()` is pretty fast for big objects (greater than 10kb).

Thoughts?

**Comment by s-munro** [comment]
The two packages look pretty solid to me, especially the first one.  I'm game to `stringify` and parse with our redis interactions.  I'm about to hop into the codebase, game for me to pick up this task?

**Comment by hrishikeshpaul** [comment]
I think if you want to pick up a task you should do the sockets refresh part, I think that's more important
